package main

import (
	"fmt"
	"gopkg.in/yaml.v2"
	"io/ioutil"
	"strings"
)

func test() {
	file, _ := ioutil.ReadFile("test.json")

	ff := strings.Replace(string(file), "music.search.SearchCgiService", "music", -1)
	//fmt.Println(string(file))
	var testt = new(AutoGeneratedB)

	err := yaml.Unmarshal([]byte(ff), testt)
	if err != nil {

	}
	fmt.Println("code: ", testt.Code)
	fmt.Println("list: ", testt)
	for _, lll := range testt.Music.Data.Body.Song.List {
		fmt.Println("in")
		fmt.Println(lll.ID)
		fmt.Println(lll.Mid)
		fmt.Println(lll.Album.Title)
		fmt.Println(lll.Album.Name)
		for _, singer := range lll.Singer {
			fmt.Println(singer.Name)
		}
	}
	fmt.Println("out")
}
